### ISSUE TITLE
Resent Client keeps crashing

### ISSUE THREAD

**Issue by Chickpea-cyber** [ThisIsALegitUsername/Resent-web#57]
So each time i choose a texture pack and start launching the client it launches to the Mojang screen and it crashes and it doesn't work even with the default texture pack for Minecraft 1.5.2 also i tried mostly all the texture. Please can you fix this issue thank you.

**Comment by 3kh0** [comment]
what device do you have?

**Comment by Chickpea-cyber** [comment]
A chromebook

**Comment by Chickpea-cyber** [comment]
Is the issue with my device or with the client thank you for responding.

**Comment by the9four** [comment]
I have a friend who kept crashing on resent at school today but I didn't for some reason

**Comment by Ironbrodiet** [comment]
Same, its been working fine until now where it crashes whenever I join. (I have been using the same device. )

**Comment by Chickpea-cyber** [comment]
ya its very annoying because i used to use presicion client but then i changed to this but it doesnt want to work

**Comment by 3kh0** [comment]
I was able to reproduce this! Crash report:
```
Resent crashed! Please dm hooman#1196 about this crash. If you're launching for the first time, don't worry! Just refresh and you'll be fine! Github: https://github.com/ThisIsALegitUsername/Resent-web

java.lang.RuntimeException: (JavaScript) TypeError: Cannot read properties of null (reading '$enabled')

TypeError: Cannot read properties of null (reading '$enabled')
    at nms_MathHelper_cos (https://resclient.vercel.app/classes.js:148247:30)
    at nlea_EaglerAdapterImpl2_setListenerPos (https://resclient.vercel.app/classes.js:87579:13)
    at nms_SoundManager_setListener (https://resclient.vercel.app/classes.js:102076:13)
    at nmc_Minecraft_runGameLoop (https://resclient.vercel.app/classes.js:93759:9)
    at nmc_Minecraft_run (https://resclient.vercel.app/classes.js:93676:9)
    at nle_Client_run0 (https://resclient.vercel.app/classes.js:1522:9)
    at nle_Client_newMain (https://resclient.vercel.app/classes.js:1333:17)
    at nle_Client_main (https://resclient.vercel.app/classes.js:1203:17)
    at TeaVMThread.runner (https://resclient.vercel.app/classes.js:458:15)
    at TeaVMThread.run (https://resclient.vercel.app/classes.js:295634:23)

eaglercraft.version = "22w43a"
eaglercraft.username = "YeelerVigg32"

webgl.version = WebGL 2.0 (OpenGL ES 3.0 Chromium)
webgl.renderer = AMD STONEY (LLVM 12.0.1, DRM 3.42, 5.10.142-19743-gd301e86c39f7)
webgl.vendor = AMD

webgl.anisotropicGlitch = false

window.eaglercraftOpts = {"container":"game_frame","assetsURI":"packs/redberyl.epk","serverWorkerURI":"worker_bootstrap.js","worldsFolder":"MAIN","servers":[{"serverName":"Blobcraft","serverAddress":"wss://blobcraft.minecraft.pe","hideAddress":true},{"serverName":"LegendSMP","serverAddress":"wss://legendsmp.minecraft.pe","hideAddress":true},{"serverName":"Hyper Network","serverAddress":"wss://hyper-network.me","hideAddress":true}],"relays":[{"addr":"wss://relay.deev.is/","name":"lax1dude relay #1","primary":false},{"addr":"wss://relay.lax1dude.net/","name":"lax1dude relay #2","primary":false},{"addr":"wss://relay.shhnowisnottheti.me/","name":"ayunami relay #1","primary":true}],"mainMenu":{"splashes":["Press Y to open GUI!"],"eaglerLogo":false}}

window.navigator.userAgent = Mozilla/5.0 (X11; CrOS x86_64 15117.111.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
window.navigator.vendor = Google Inc.
window.navigator.language = en-US
window.navigator.hardwareConcurrency = 2
window.navigator.deviceMemory = 4
window.navigator.platform = Linux x86_64
window.navigator.product = Gecko

rootElement.clientWidth = 1686
rootElement.clientHeight = 780
window.innerWidth = 1686
window.innerHeight = 780
window.outerWidth = 1517
window.outerHeight = 805
window.devicePixelRatio = 0.809999942779541
window.screen.availWidth = 1517
window.screen.availHeight = 805
window.screen.colorDepth = 24
window.screen.pixelDepth = 24

window.location.href = https://resclient.vercel.app/#

----- Begin Minecraft Config -----
CgAAAA==
----- End Minecraft Config -----

window.minecraftServer = undefined
```

**Comment by Chickpea-cyber** [comment]
Resent crashed! Please dm hooman#1196 about this crash. If you're launching for the first time, don't worry! Just refresh and you'll be fine! Github: https://github.com/ThisIsALegitUsername/Resent-web

java.lang.RuntimeException: (JavaScript) TypeError: Cannot read properties of null (reading '$enabled')

TypeError: Cannot read properties of null (reading '$enabled')
    at nms_MathHelper_cos (https://resclient.vercel.app/classes.js:148247:30)
    at nlea_EaglerAdapterImpl2_setListenerPos (https://resclient.vercel.app/classes.js:87579:13)
    at nms_SoundManager_setListener (https://resclient.vercel.app/classes.js:102076:13)
    at nmc_Minecraft_runGameLoop (https://resclient.vercel.app/classes.js:93759:9)
    at nmc_Minecraft_run (https://resclient.vercel.app/classes.js:93676:9)
    at nle_Client_run0 (https://resclient.vercel.app/classes.js:1522:9)
    at nle_Client_newMain (https://resclient.vercel.app/classes.js:1333:17)
    at nle_Client_main (https://resclient.vercel.app/classes.js:1203:17)
    at TeaVMThread.runner (https://resclient.vercel.app/classes.js:458:15)
    at TeaVMThread.run (https://resclient.vercel.app/classes.js:295634:23)
    at TeaVMThread.resume (https://resclient.vercel.app/classes.js:295628:10)
    at callback.$complete (https://resclient.vercel.app/classes.js:97894:16)
    at otpp_AsyncCallbackWrapper_complete (https://resclient.vercel.app/classes.js:104511:30)
    at jl_Thread$SleepHandler_run (https://resclient.vercel.app/classes.js:104561:9)
    at $rt_array.toString [as $run] (https://resclient.vercel.app/classes.js:292547:143)
    at otp_Platform_launchThread (https://resclient.vercel.app/classes.js:82101:15)
    at https://resclient.vercel.app/classes.js:82105:9
    at sentryWrapped (https://browser.sentry-cdn.com/6.2.2/bundle.min.js:2:53837)

eaglercraft.version = "22w43a"
eaglercraft.username = "ViggYeeish85"

webgl.version = WebGL 2.0 (OpenGL ES 3.0 Chromium)
webgl.renderer = AMD STONEY (LLVM 12.0.1, DRM 3.42, 5.10.142-19743-gd301e86c39f7)
webgl.vendor = AMD

webgl.anisotropicGlitch = false

window.eaglercraftOpts = {"container":"game_frame","assetsURI":"packs/fiizle.epk","serverWorkerURI":"worker_bootstrap.js","worldsFolder":"MAIN","servers":[{"serverName":"Blobcraft","serverAddress":"wss://blobcraft.minecraft.pe","hideAddress":true},{"serverName":"LegendSMP","serverAddress":"wss://legendsmp.minecraft.pe","hideAddress":true},{"serverName":"Hyper Network","serverAddress":"wss://hyper-network.me","hideAddress":true}],"relays":[{"addr":"wss://relay.deev.is/","name":"lax1dude relay #1","primary":false},{"addr":"wss://relay.lax1dude.net/","name":"lax1dude relay #2","primary":true},{"addr":"wss://relay.shhnowisnottheti.me/","name":"ayunami relay #1","primary":false}],"mainMenu":{"splashes":["Press Y to open GUI!"],"eaglerLogo":false}}

window.navigator.userAgent = Mozilla/5.0 (X11; CrOS x86_64 15117.111.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
window.navigator.vendor = Google Inc.
window.navigator.language = en-US
window.navigator.hardwareConcurrency = 2
window.navigator.deviceMemory = 4
window.navigator.platform = Linux x86_64
window.navigator.product = Gecko

rootElement.clientWidth = 1518
rootElement.clientHeight = 750
window.innerWidth = 1517
window.innerHeight = 750
window.outerWidth = 1517
window.outerHeight = 853
window.devicePixelRatio = 0.8999999761581421
window.screen.availWidth = 1517
window.screen.availHeight = 853
window.screen.colorDepth = 24
window.screen.pixelDepth = 24

window.location.href = https://resclient.vercel.app/#

----- Begin Minecraft Config -----
CgAAAA==
----- End Minecraft Config -----

window.minecraftServer = undefined

**Comment by Chickpea-cyber** [comment]
This is my crash report

**Comment by Ironbrodiet** [comment]
Resent crashed! Please dm hooman#1196 about this crash. If you're launching for the first time, don't worry! Just refresh and you'll be fine! Github: https://github.com/ThisIsALegitUsername/Resent-web

java.lang.RuntimeException: (JavaScript) TypeError: Cannot read properties of null (reading '$enabled')

TypeError: Cannot read properties of null (reading '$enabled')
    at nms_MathHelper_cos (https://resclient.vercel.app/classes.js:148247:30)
    at nlea_EaglerAdapterImpl2_setListenerPos (https://resclient.vercel.app/classes.js:87579:13)
    at nms_SoundManager_setListener (https://resclient.vercel.app/classes.js:102076:13)
    at nmc_Minecraft_runGameLoop (https://resclient.vercel.app/classes.js:93759:9)
    at nmc_Minecraft_run (https://resclient.vercel.app/classes.js:93676:9)
    at nle_Client_run0 (https://resclient.vercel.app/classes.js:1522:9)
    at nle_Client_newMain (https://resclient.vercel.app/classes.js:1333:17)
    at nle_Client_main (https://resclient.vercel.app/classes.js:1203:17)
    at TeaVMThread.runner (https://resclient.vercel.app/classes.js:458:15)
    at TeaVMThread.run (https://resclient.vercel.app/classes.js:295634:23)

eaglercraft.version = "22w43a"
eaglercraft.username = "DarvlerYeeish54"

webgl.version = WebGL 2.0 (OpenGL ES 3.0 Chromium)
webgl.renderer = Mesa DRI Intel(R) UHD Graphics 600 (GLK 2)
webgl.vendor = Intel Open Source Technology Center

webgl.anisotropicGlitch = false

window.eaglercraftOpts = {"container":"game_frame","assetsURI":"packs/thelegend.epk","serverWorkerURI":"worker_bootstrap.js","worldsFolder":"MAIN","servers":[{"serverName":"Blobcraft","serverAddress":"wss://blobcraft.minecraft.pe","hideAddress":true},{"serverName":"LegendSMP","serverAddress":"wss://legendsmp.minecraft.pe","hideAddress":true},{"serverName":"Hyper Network","serverAddress":"wss://hyper-network.me","hideAddress":true}],"relays":[{"addr":"wss://relay.deev.is/","name":"lax1dude relay #1","primary":false},{"addr":"wss://relay.lax1dude.net/","name":"lax1dude relay #2","primary":true},{"addr":"wss://relay.shhnowisnottheti.me/","name":"ayunami relay #1","primary":false}],"mainMenu":{"splashes":["Press Y to open GUI!"],"eaglerLogo":false}}

window.navigator.userAgent = Mozilla/5.0 (X11; CrOS x86_64 14695.148.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
window.navigator.vendor = Google Inc.
window.navigator.language = en-US
window.navigator.hardwareConcurrency = 4
window.navigator.deviceMemory = 4
window.navigator.platform = Linux x86_64
window.navigator.product = Gecko

rootElement.clientWidth = 1366
rootElement.clientHeight = 768
window.innerWidth = 1366
window.innerHeight = 768
window.outerWidth = 1366
window.outerHeight = 768
window.devicePixelRatio = 1
window.screen.availWidth = 1366
window.screen.availHeight = 768
window.screen.colorDepth = 24
window.screen.pixelDepth = 24

window.location.href = https://resclient.vercel.app/#

----- Begin Minecraft Config -----
CgAAAA==
----- End Minecraft Config -----

window.minecraftServer = undefined


**This is my crash report**

**Comment by ThisIsALegitUsername** [comment]
I have fixed this. Thanks for the report.
