### ISSUE TITLE
kept on crashing

### ISSUE THREAD

**Issue by CuriousCoder1232** [ThisIsALegitUsername/Resent-web#60]
Resent crashed! Please dm hooman#1196 about this crash. If you're launching for the first time, don't worry! Just refresh and you'll be fine! Github: https://github.com/ThisIsALegitUsername/Resent-web

java.lang.RuntimeException: (JavaScript) TypeError: Cannot read properties of null (reading '$enabled')

TypeError: Cannot read properties of null (reading '$enabled')
    at nms_MathHelper_cos (https://resclient.vercel.app/classes.js:148247:30)
    at nlea_EaglerAdapterImpl2_setListenerPos (https://resclient.vercel.app/classes.js:87579:13)
    at nms_SoundManager_setListener (https://resclient.vercel.app/classes.js:102076:13)
    at nmc_Minecraft_runGameLoop (https://resclient.vercel.app/classes.js:93759:9)
    at nmc_Minecraft_run (https://resclient.vercel.app/classes.js:93676:9)
    at nle_Client_run0 (https://resclient.vercel.app/classes.js:1522:9)
    at nle_Client_newMain (https://resclient.vercel.app/classes.js:1333:17)
    at nle_Client_main (https://resclient.vercel.app/classes.js:1203:17)
    at TeaVMThread.runner (https://resclient.vercel.app/classes.js:458:15)
    at TeaVMThread.run (https://resclient.vercel.app/classes.js:295634:23)
    at TeaVMThread.resume (https://resclient.vercel.app/classes.js:295628:10)
    at callback.$complete (https://resclient.vercel.app/classes.js:97894:16)
    at otpp_AsyncCallbackWrapper_complete (https://resclient.vercel.app/classes.js:104511:30)
    at jl_Thread$SleepHandler_run (https://resclient.vercel.app/classes.js:104561:9)
    at $rt_array.toString [as $run] (https://resclient.vercel.app/classes.js:292547:143)
    at otp_Platform_launchThread (https://resclient.vercel.app/classes.js:82101:15)
    at https://resclient.vercel.app/classes.js:82105:9
    at sentryWrapped (https://browser.sentry-cdn.com/6.2.2/bundle.min.js:2:53837)

eaglercraft.version = "22w43a"
eaglercraft.username = "YeeDarver29"

webgl.version = WebGL 2.0 (OpenGL ES 3.0 Chromium)
webgl.renderer = Mesa DRI Intel(R) UHD Graphics 600 (GLK 2)
webgl.vendor = Intel Open Source Technology Center

webgl.anisotropicGlitch = false

window.eaglercraftOpts = {"container":"game_frame","assetsURI":"packs/fiizle.epk","serverWorkerURI":"worker_bootstrap.js","worldsFolder":"MAIN","servers":[{"serverName":"Blobcraft","serverAddress":"wss://blobcraft.minecraft.pe","hideAddress":true},{"serverName":"LegendSMP","serverAddress":"wss://legendsmp.minecraft.pe","hideAddress":true},{"serverName":"Hyper Network","serverAddress":"wss://hyper-network.me","hideAddress":true}],"relays":[{"addr":"wss://relay.deev.is/","name":"lax1dude relay #1","primary":true},{"addr":"wss://relay.lax1dude.net/","name":"lax1dude relay #2","primary":false},{"addr":"wss://relay.shhnowisnottheti.me/","name":"ayunami relay #1","primary":false}],"mainMenu":{"splashes":["Press Y to open GUI!"],"eaglerLogo":false}}

window.navigator.userAgent = Mozilla/5.0 (X11; CrOS x86_64 15117.111.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
window.navigator.vendor = Google Inc.
window.navigator.language = en-US
window.navigator.hardwareConcurrency = 2
window.navigator.deviceMemory = 4
window.navigator.platform = Linux x86_64
window.navigator.product = Gecko

rootElement.clientWidth = 1366
rootElement.clientHeight = 665
window.innerWidth = 1366
window.innerHeight = 665
window.outerWidth = 1366
window.outerHeight = 768
window.devicePixelRatio = 1
window.screen.availWidth = 1366
window.screen.availHeight = 768
window.screen.colorDepth = 24
window.screen.pixelDepth = 24

window.location.href = https://resclient.vercel.app/#

----- Begin Minecraft Config -----
CgAAAA==
----- End Minecraft Config -----

window.minecraftServer = undefined

**Comment by cooldude-222** [comment]
I am having the same issue

**Comment by ThisIsALegitUsername** [comment]
try again, should be fixed

**Comment by CuriousCoder1232** [comment]
thx

**Comment by 3kh0** [comment]
@CuriousCoder1232 Please close this if this fixed the issue
